### ISSUE TITLE
立ち絵についての要望

### ISSUE THREAD

**Issue by nagisads** [entyu/udonarium_lily#3]
初めまして。そうそうこういうのが欲しかったんだという素晴らしい改造版をありがとうございます。
TwitterのDMが相互フォローでないと送れない設定の様なのでこちらに気になった点を送らせていただきます。

立ち絵が表示出来、差分の切り替えなども簡単で良いのですが、表示がチャットウィンドウと一体だとチャットログを圧迫してしまい、ログを多めに表示しようとするとマップの表示領域が大きく減ってしまいます。
某どどんとふの様に、ウィンドウ外に表示＆クリックで簡単に消せるorチャットウィンドウと独立したウィンドウで表示するなど、画面を圧迫しなくなったら良いなと思いました。
それが不可能であればですが、立ち絵の表示位置がログの下ですと、入力欄とログで視点の移動が大きくなり疲れるため、表示位置を上か下で選べる様な設定があるととても助かります。
出来ればご検討よろしくお願いします。

**Comment by entyu** [comment]
ご意見ありがとうございます。
どどんとふと同様の配置(チャットウィンドウの上に出す、クリックで消す、マウスがチャットウィンドウを離れたら一時非表示)は、試してみたところ実装可能と判断できました。
現状の配置の切り替えが行えるように、次のバージョンアップで改造しようと思います。

**Comment by entyu** [comment]
v1.01.0にて本機能を実装しました。ご意見ありがとうございました
