### ISSUE TITLE
簡易ログ実装の新機能テスト版の不具合について

### ISSUE THREAD

**Issue by nanasisama** [entyu/udonarium_lily#4]
現在ユドナリウムリリィをTRPGセッションで頻繁に利用させていただいています
文字色がつくと聞き新機能を使わせていただいたところログが更新されるとログの表示が最新のコメントではなく上の行にある前のコメントにフォーカスされるようになっていました
同じ部屋にいた多くの人が同じ症状が出ています
他の環境で再現性があるかまでは確認していないため、よろしければ検証おねがいします
現状もっとも卓環境にあっているツールであるため開発期待しています

**Comment by nanasisama** [comment]
発生環境：Windows10　Vivaldi　同時接続8人
同卓者はChromeが主体でした

**Comment by entyu** [comment]
レポートありがとうございます。
masterブランチのコードですとログを一行表示に切り替える機能で、ログの縦方向の長さの計算式を変更しているため、おそらくその影響と思われます。
計算式を見直しておきます。

**Comment by entyu** [comment]
v1.01.0にて最新行がフォーカスされる様、修正いたしました。レポートありがとうございました。
