### ISSUE TITLE
ルーム入室時の挙動について・他要望

### ISSUE THREAD

**Issue by Chrono960** [entyu/udonarium_lily#6]
ユドナリウムリリィ、大変便利に使用させていただいております。
利用に当たって３つほど仕様の要望を送らせていただきたく。

・ロビーからルームに入室する際、ロビーに読み込んだデータがある際の引き継ぎの確認（或いは入室時のワンクッション）
・立ち絵を表示中のチャットウィンドウからマウスカーソルを離しても立ち絵の表示を継続する機能
・共有メモの平面化・及びポップアップの表示固定

可能ならばでよいので、ご考慮いただけると幸いです。

**Comment by entyu** [comment]
ご意見ありがとうございます。

＞ロビーからルームに入室する際、ロビーに読み込んだデータがある際の引き継ぎの確認（或いは入室時のワンクッション）
意図を読み取れなかった部分があるので確認させてください。
入室する際には
「ルーム一覧を表示」「ルーム選択」「実プレイ環境では高確率でパスワード入力要求」がなされます。
1、この状況で入室するということは明確に入室する意志を持っているはずですので、追加の警告ウィンドウを出しても勢いでYESを押す可能性が高いのではないかと思っています
2、ロードしたデータが有るならばそのデータはZIPでお持ちのはずなので読み直せば復旧は可能かと思います

必要となるケースが
自分がGMのための部屋データをロードして改造作業した際に、セーブせずにそのままほかセッションに呼ばれて参加しようとした。ぐらいしか私は思いつけなかったのですが、必要となるケースの操作手順の具体例（実際にどのような状況で欲しいと思ったのか）を教えていただけますでしょうか。

＞立ち絵を表示中のチャットウィンドウからマウスカーソルを離しても立ち絵の表示を継続する機能
画面が狭くで背景のコマなどを操作する際は消えたほうが良い派の方も居るので、詳細設定に選択オプションを付ける方向で考えてみます。

＞共有メモの平面化
共有メモの平面化はそのままパタンと地面と並行になるように倒して表示する、
リアルで言うところのゲームテーブルにPOPをたてるのではなくメモ用紙をそのままテーブルに並べるイメージであってますでしょうか。
そうであれば「地面と平行に表示する」の設定項目の追加を検討してみます。

＞・及びポップアップの表示固定
この情報はじっくり考えたい、このルールサマリーは表示しっぱなしにしたいな等をPLが思ったときに、
チャットウィンドウ等と同様に、自分で閉じるまで消えない表示に出来る機能ということですよね。
実装検討してみます。

**Comment by Chrono960** [comment]
検討ありがとうございます、同時に言葉足らずの要望提出で申し訳なく。

＞＞ロビーからルームに入室する際、ロビーに読み込んだデータがある際の引き継ぎの確認（或いは入室時のワンクッション）

＞必要となるケースが
＞自分がGMのための部屋データをロードして改造作業した際に、セーブせずにそのままほかセッションに呼ばれて参加しようとした。ぐらいしか私は思いつけなかったのですが、必要となるケースの操作手順の具体例（実際にどのような状況で欲しいと思ったのか）を教えていただけますでしょうか。

認識としてはその通りで、そういった操作ミスでのデータの流入を防ぎたいということ、だったのですが。
失礼しました。此方でこの要望を投げるに辺り私のプレイグループで出た話を誤解していました。
「同じゆどなりうむで開催された卓を見学しようとした時に
　別卓の準備の為別ウィンドウでやろうとした準備のための全データ入のZIPを
　そのウィンドウ内に取り込みチャットログなどの削除（上書き）」
が起きてしまった事例を、私が「ロビーからの入室の際での部屋情報持ち込み」が起こせてしまうことと誤解していた次第です。
その為申し訳ないのですが、「入室した部屋でZIPの読み込みなどをしない」状態、どどんとふであったような見学機能（発言やチャットログなどを読むことだけができる）に似た状態を実装することは可能でしょうか、とこちらの要望を改めさせていただきたいです。

＞＞共有メモの平面化
＞共有メモの平面化はそのままパタンと地面と並行になるように倒して表示する、
＞リアルで言うところのゲームテーブルにPOPをたてるのではなくメモ用紙をそのままテーブルに並べるイメージであってますでしょうか。
＞そうであれば「地面と平行に表示する」の設定項目の追加を検討してみます。
その通りです。記載量が多いとき、縦の伸びたメモの参照性が悪くなることがありました。
この際「テーブルの横合いに並べておくようにできたらな……」と感じた為です。

＞立ち絵を表示中のチャットウィンドウからマウスカーソルを離しても立ち絵の表示を継続する機能
＞ポップアップの表示固定
こちら２つはそのままそのような要望でした、検討ありがとうございます。


日々楽しく遊ぶ為にとても活用させていただいております、改めて感謝を。

**Comment by entyu** [comment]
ヒアリんしてきていただきありがとうございます。

＞「入室した部屋でZIPの読み込みなどをしない」状態、どどんとふであったような見学機能（発言やチャットログなどを読むことだけができる）に似た状態を実装することは可能でしょうか、とこちらの要望を改めさせていただきたいです。

状況は理解できました。現状はプレイ中の部屋に部屋データを投げ込むと一発で不可逆なデータ更新してしまいますね。
これをやってしまった話は他の方からも聞いたことがあります。
見学モードはユドナリウム側で想定していなかったであろう作りなので、作るとなると大改修になります。(要望自体は別所からも有るのですが)大規模のため一時見送りとしています。

部屋データの投げ込みがセッション進行を致命的に破壊すると思うので、
セッション中＝部屋を作成済み状態(ルーム一覧に部屋が出る状態)　での部屋データのロードで
「セッション中のようですが本当に読み込んでいいですか？」のようなアラートが出せるか？の方向で検討してみます。

**Comment by Chrono960** [comment]
ありがとうございます！

**Comment by entyu** [comment]
複数項目にまたがっておりある程度実装完了したこと、残件も他の方からの要望と同様の内容もあるため解決としてクローズします
